# Generated by Django 2.2.3 on 2019-07-18 18:13

from bible_lib import BibleBooks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblereference',
            name='book',
            field=models.CharField(choices=[(BibleBooks('Genesis'), 'Genesis'), (BibleBooks('Exodus'), 'Exodus'), (BibleBooks('Leviticus'), 'Leviticus'), (BibleBooks('Numbers'), 'Numbers'), (BibleBooks('Deuteronomy'), 'Deuteronomy'), (BibleBooks('Joshua'), 'Joshua'), (BibleBooks('Judges'), 'Judges'), (BibleBooks('Ruth'), 'Ruth'), (BibleBooks('1 Samuel'), '1 Samuel'), (BibleBooks('2 Samuel'), '2 Samuel'), (BibleBooks('1 Kings'), '1 Kings'), (BibleBooks('2 Kings'), '2 Kings'), (BibleBooks('1 Chronicles'), '1 Chronicles'), (BibleBooks('2 Chronicles'), '2 Chronicles'), (BibleBooks('Ezra'), 'Ezra'), (BibleBooks('Nehemiah'), 'Nehemiah'), (BibleBooks('Esther'), 'Esther'), (BibleBooks('Job'), 'Job'), (BibleBooks('Psalms'), 'Psalms'), (BibleBooks('Proverbs'), 'Proverbs'), (BibleBooks('Ecclesiastes'), 'Ecclesiastes'), (BibleBooks('Song of Solomon'), 'Song of Solomon'), (BibleBooks('Isaiah'), 'Isaiah'), (BibleBooks('Jeremiah'), 'Jeremiah'), (BibleBooks('Lamentations'), 'Lamentations'), (BibleBooks('Ezekiel'), 'Ezekiel'), (BibleBooks('Daniel'), 'Daniel'), (BibleBooks('Hosea'), 'Hosea'), (BibleBooks('Joel'), 'Joel'), (BibleBooks('Amos'), 'Amos'), (BibleBooks('Obadiah'), 'Obadiah'), (BibleBooks('Jonah'), 'Jonah'), (BibleBooks('Micah'), 'Micah'), (BibleBooks('Nahum'), 'Nahum'), (BibleBooks('Habakkuk'), 'Habakkuk'), (BibleBooks('Zephaniah'), 'Zephaniah'), (BibleBooks('Haggai'), 'Haggai'), (BibleBooks('Zechariah'), 'Zechariah'), (BibleBooks('Malachi'), 'Malachi'), (BibleBooks('Matthew'), 'Matthew'), (BibleBooks('Mark'), 'Mark'), (BibleBooks('Luke'), 'Luke'), (BibleBooks('John'), 'John'), (BibleBooks('Acts (of the Apostles)'), 'Acts (of the Apostles)'), (BibleBooks('Romans'), 'Romans'), (BibleBooks('1 Corinthians'), '1 Corinthians'), (BibleBooks('2 Corinthians'), '2 Corinthians'), (BibleBooks('Galatians'), 'Galatians'), (BibleBooks('Ephesians'), 'Ephesians'), (BibleBooks('Philippians'), 'Philippians'), (BibleBooks('Colossians'), 'Colossians'), (BibleBooks('1 Thessalonians'), '1 Thessalonians'), (BibleBooks('2 Thessalonians'), '2 Thessalonians'), (BibleBooks('1 Timothy'), '1 Timothy'), (BibleBooks('2 Timothy'), '2 Timothy'), (BibleBooks('Titus'), 'Titus'), (BibleBooks('Philemon'), 'Philemon'), (BibleBooks('Hebrews'), 'Hebrews'), (BibleBooks('James'), 'James'), (BibleBooks('1 Peter'), '1 Peter'), (BibleBooks('2 Peter'), '2 Peter'), (BibleBooks('1 John'), '1 John'), (BibleBooks('2 John'), '2 John'), (BibleBooks('3 John'), '3 John'), (BibleBooks('Jude'), 'Jude'), (BibleBooks('Revelation'), 'Revelation')], default=BibleBooks('Genesis'), max_length=32),
        ),
    ]
