# Generated by Django 2.2.3 on 2019-07-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callings_app', '0003_auto_20190718_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.ImageField(upload_to='images/')),
                ('calling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callings_app.Calling')),
            ],
        ),
    ]
