# Generated by Django 2.2.3 on 2019-07-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callings_app', '0006_auto_20190720_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarybiblereference',
            name='is_primary_reference',
        ),
        migrations.RemoveField(
            model_name='secondarybiblereference',
            name='is_primary_reference',
        ),
    ]
