# Generated by Django 2.2.3 on 2019-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callings_app', '0007_auto_20190720_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='calling',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
