# Generated by Django 2.2.3 on 2019-07-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandment',
            name='description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='commandment',
            name='description_nl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='commandment',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='commandment',
            name='title_nl',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
