# Generated by Django 2.2.3 on 2019-08-07 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0003_auto_20190805_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('file', models.URLField()),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='videos/')),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SongUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('file', models.URLField()),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SermonUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('file', models.URLField()),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('file', models.URLField()),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('file', models.URLField()),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
