# Generated by Django 4.2.5 on 2023-11-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0002_biblereference_bibletranslationmetadata_commandment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='related_step_description',
            field=models.CharField(blank=True, default=None, help_text='A description why this step is related to the Lesson from the Childrens Bible', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='story',
            field=models.CharField(blank=True, default=None, help_text='The title of the lesson from the Childrens Bible', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='The step of the lesson which will be learned', max_length=256),
        ),
    ]
