# Generated by Django 2.2.4 on 2019-09-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0002_blog_book_commandment_drawing_file_movie_picture_primarybiblereference_question_redirect_secondarybi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('commandment', 'title', 'author', 'url', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('commandment', 'title', 'author', 'url', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='drawing',
            unique_together={('commandment', 'title', 'author', 'url', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('commandment', 'title', 'author', 'url', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together={('commandment', 'title', 'author', 'url', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('commandment', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='secondarybiblereference',
            unique_together={('commandment', 'book', 'begin_chapter', 'begin_verse', 'end_chapter', 'end_verse')},
        ),
        migrations.AlterUniqueTogether(
            name='sermon',
            unique_together={('commandment', 'title', 'author', 'url', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='shortmovie',
            unique_together={('commandment', 'title', 'author', 'url', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('commandment', 'title', 'author', 'url', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='tertiarybiblereference',
            unique_together={('commandment', 'book', 'begin_chapter', 'begin_verse', 'end_chapter', 'end_verse')},
        ),
        migrations.AlterUniqueTogether(
            name='testimony',
            unique_together={('commandment', 'title', 'author', 'url', 'language')},
        ),
    ]
