# Generated by Django 2.2.6 on 2019-11-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0002_biblereference_blog_book_commandment_directbiblereference_drawing_duplicatebiblereference_examplebib'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleTranslationMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_id', models.CharField(default='', max_length=32, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
