# Generated by Django 2.2.6 on 2020-03-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0002_biblereference_bibletranslationmetadata_blog_book_commandment_directbiblereference_drawing_duplicate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandment',
            name='devotional',
        ),
        migrations.RemoveField(
            model_name='commandment',
            name='devotional_source',
        ),
    ]
