# Generated by Django 2.2.6 on 2020-01-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0002_biblereference_bibletranslationmetadata_blog_book_commandment_directbiblereference_drawing_duplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblereference',
            name='author',
            field=models.CharField(default='Undetermined', max_length=64),
        ),
        migrations.AlterField(
            model_name='biblereference',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='target_audience',
            field=models.CharField(choices=[('any', 'any'), ('adults', 'adults'), ('kids', 'kids')], default='any', max_length=32),
        ),
        migrations.AlterField(
            model_name='book',
            name='target_audience',
            field=models.CharField(choices=[('any', 'any'), ('adults', 'adults'), ('kids', 'kids')], default='any', max_length=32),
        ),
        migrations.AlterField(
            model_name='directbiblereference',
            name='author',
            field=models.CharField(default='Undetermined', max_length=64),
        ),
        migrations.AlterField(
            model_name='directbiblereference',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='target_audience',
            field=models.CharField(choices=[('any', 'any'), ('adults', 'adults'), ('kids', 'kids')], default='any', max_length=32),
        ),
        migrations.AlterField(
            model_name='duplicatebiblereference',
            name='author',
            field=models.CharField(default='Undetermined', max_length=64),
        ),
        migrations.AlterField(
            model_name='duplicatebiblereference',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='examplebiblereference',
            name='author',
            field=models.CharField(default='Undetermined', max_length=64),
        ),
        migrations.AlterField(
            model_name='examplebiblereference',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='indirectbiblereference',
            name='author',
            field=models.CharField(default='Undetermined', max_length=64),
        ),
        migrations.AlterField(
            model_name='indirectbiblereference',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='target_audience',
            field=models.CharField(choices=[('any', 'any'), ('adults', 'adults'), ('kids', 'kids')], default='any', max_length=32),
        ),
        migrations.AlterField(
            model_name='picture',
            name='target_audience',
            field=models.CharField(choices=[('any', 'any'), ('adults', 'adults'), ('kids', 'kids')], default='any', max_length=32),
        ),
        migrations.AlterField(
            model_name='primarybiblereference',
            name='author',
            field=models.CharField(default='Undetermined', max_length=64),
        ),
        migrations.AlterField(
            model_name='primarybiblereference',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='target_audience',
            field=models.CharField(choices=[('any', 'any'), ('adults', 'adults'), ('kids', 'kids')], default='any', max_length=32),
        ),
        migrations.AlterField(
            model_name='shortmovie',
            name='target_audience',
            field=models.CharField(choices=[('any', 'any'), ('adults', 'adults'), ('kids', 'kids')], default='any', max_length=32),
        ),
        migrations.AlterField(
            model_name='song',
            name='target_audience',
            field=models.CharField(choices=[('any', 'any'), ('adults', 'adults'), ('kids', 'kids')], default='any', max_length=32),
        ),
        migrations.AlterField(
            model_name='studybiblereference',
            name='author',
            field=models.CharField(default='Undetermined', max_length=64),
        ),
        migrations.AlterField(
            model_name='studybiblereference',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='superbook',
            name='target_audience',
            field=models.CharField(choices=[('any', 'any'), ('adults', 'adults'), ('kids', 'kids')], default='any', max_length=32),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='target_audience',
            field=models.CharField(choices=[('any', 'any'), ('adults', 'adults'), ('kids', 'kids')], default='any', max_length=32),
        ),
    ]
