# Generated by Django 2.2.6 on 2020-03-29 14:27

import commandments_app.models.bible_books
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0003_auto_20200319_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biblereference',
            old_name='origin',
            new_name='ot_rambam_id',
        ),
        migrations.RenameField(
            model_name='directbiblereference',
            old_name='origin',
            new_name='ot_rambam_id',
        ),
        migrations.RenameField(
            model_name='duplicatebiblereference',
            old_name='origin',
            new_name='ot_rambam_id',
        ),
        migrations.RenameField(
            model_name='examplebiblereference',
            old_name='origin',
            new_name='ot_rambam_id',
        ),
        migrations.RenameField(
            model_name='indirectbiblereference',
            old_name='origin',
            new_name='ot_rambam_id',
        ),
        migrations.RenameField(
            model_name='primarybiblereference',
            old_name='origin',
            new_name='ot_rambam_id',
        ),
        migrations.RenameField(
            model_name='studybiblereference',
            old_name='origin',
            new_name='ot_rambam_id',
        ),
        migrations.AddField(
            model_name='biblereference',
            name='ot_nr',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='biblereference',
            name='ot_rambam_title',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='directbiblereference',
            name='ot_nr',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='directbiblereference',
            name='ot_rambam_title',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='duplicatebiblereference',
            name='ot_nr',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='duplicatebiblereference',
            name='ot_rambam_title',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='examplebiblereference',
            name='ot_nr',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='examplebiblereference',
            name='ot_rambam_title',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='indirectbiblereference',
            name='ot_nr',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='indirectbiblereference',
            name='ot_rambam_title',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='primarybiblereference',
            name='ot_nr',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='primarybiblereference',
            name='ot_rambam_title',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studybiblereference',
            name='ot_nr',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studybiblereference',
            name='ot_rambam_title',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='OTLawBibleReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('Genesis', 'Genesis'), ('Exodus', 'Exodus'), ('Leviticus', 'Leviticus'), ('Numbers', 'Numbers'), ('Deuteronomy', 'Deuteronomy'), ('Joshua', 'Joshua'), ('Judges', 'Judges'), ('Ruth', 'Ruth'), ('SamuelFirstBook', '1 Samuel'), ('SamuelSecondBook', '2 Samuel'), ('KingsFirstBook', '1 Kings'), ('KingsSecondBook', '2 Kings'), ('ChroniclesFirstBook', '1 Chronicles'), ('ChroniclesSecondBook', '2 Chronicles'), ('Ezra', 'Ezra'), ('Nehemiah', 'Nehemiah'), ('Esther', 'Esther'), ('Job', 'Job'), ('Psalms', 'Psalms'), ('Proverbs', 'Proverbs'), ('Ecclesiastes', 'Ecclesiastes'), ('SongOfSolomon', 'Song of Solomon'), ('Isaiah', 'Isaiah'), ('Jeremiah', 'Jeremiah'), ('Lamentations', 'Lamentations'), ('Ezekiel', 'Ezekiel'), ('Daniel', 'Daniel'), ('Hosea', 'Hosea'), ('Joel', 'Joel'), ('Amos', 'Amos'), ('Obadiah', 'Obadiah'), ('Jonah', 'Jonah'), ('Micah', 'Micah'), ('Nahum', 'Nahum'), ('Habakkuk', 'Habakkuk'), ('Zephaniah', 'Zephaniah'), ('Haggai', 'Haggai'), ('Zechariah', 'Zechariah'), ('Malachi', 'Malachi'), ('Matthew', 'Matthew'), ('Mark', 'Mark'), ('Luke', 'Luke'), ('John', 'John'), ('Acts', 'Acts'), ('Romans', 'Romans'), ('CorinthiansFirstBook', '1 Corinthians'), ('CorinthiansSecondBook', '2 Corinthians'), ('Galatians', 'Galatians'), ('Ephesians', 'Ephesians'), ('Philippians', 'Philippians'), ('Colossians', 'Colossians'), ('ThessaloniansFirstBook', '1 Thessalonians'), ('ThessaloniansSecondBook', '2 Thessalonians'), ('TimothyFirstBook', '1 Timothy'), ('TimothySecondBook', '2 Timothy'), ('Titus', 'Titus'), ('Philemon', 'Philemon'), ('Hebrews', 'Hebrews'), ('James', 'James'), ('PeterFirstBook', '1 Peter'), ('PeterSecondBook', '2 Peter'), ('JohnFirstBook', '1 John'), ('JohnSecondBook', '2 John'), ('JohnThirdBook', '3 John'), ('Jude', 'Jude'), ('Revelation', 'Revelation')], default=commandments_app.models.bible_books.BibleBooks('Genesis'), max_length=32)),
                ('begin_chapter', models.IntegerField(default=1)),
                ('begin_verse', models.IntegerField(default=1)),
                ('end_chapter', models.IntegerField(default=0)),
                ('end_verse', models.IntegerField(default=0)),
                ('ot_nr', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('ot_rambam_id', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('ot_rambam_title', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('author', models.CharField(default='Undetermined', max_length=64)),
                ('positive_negative', models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', max_length=32)),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
            options={
                'unique_together': {('commandment', 'book', 'begin_chapter', 'begin_verse', 'end_chapter', 'end_verse', 'ot_nr', 'ot_rambam_id', 'ot_rambam_title')},
            },
        ),
    ]
