# Generated by Django 4.2.5 on 2023-12-02 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0003_lesson_related_step_description_lesson_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='activities',
            field=ckeditor.fields.RichTextField(blank=True, default=None, help_text='Beschrijf bij de les horende actititeiten of verwerkingsopdrachten', null=True),
        ),
    ]
