# Generated by Django 2.2.6 on 2019-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0003_bibletranslationmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblereference',
            name='literal_figurative',
            field=models.CharField(choices=[('literal', 'literal'), ('figurative', 'figurative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='biblereference',
            name='origin',
            field=models.CharField(default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='biblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='directbiblereference',
            name='literal_figurative',
            field=models.CharField(choices=[('literal', 'literal'), ('figurative', 'figurative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='directbiblereference',
            name='origin',
            field=models.CharField(default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='directbiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='duplicatebiblereference',
            name='literal_figurative',
            field=models.CharField(choices=[('literal', 'literal'), ('figurative', 'figurative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='duplicatebiblereference',
            name='origin',
            field=models.CharField(default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='duplicatebiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='examplebiblereference',
            name='literal_figurative',
            field=models.CharField(choices=[('literal', 'literal'), ('figurative', 'figurative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='examplebiblereference',
            name='origin',
            field=models.CharField(default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='examplebiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='indirectbiblereference',
            name='literal_figurative',
            field=models.CharField(choices=[('literal', 'literal'), ('figurative', 'figurative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='indirectbiblereference',
            name='origin',
            field=models.CharField(default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='indirectbiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='primarybiblereference',
            name='literal_figurative',
            field=models.CharField(choices=[('literal', 'literal'), ('figurative', 'figurative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='primarybiblereference',
            name='origin',
            field=models.CharField(default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='primarybiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='studybiblereference',
            name='literal_figurative',
            field=models.CharField(choices=[('literal', 'literal'), ('figurative', 'figurative'), ('both', 'both')], default='positive', max_length=32),
        ),
        migrations.AddField(
            model_name='studybiblereference',
            name='origin',
            field=models.CharField(default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='studybiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', max_length=32),
        ),
    ]
