# Generated by Django 2.2.6 on 2020-04-04 14:01

import commandments_app.models.commandment_categories
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0003_auto_20200404_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandment',
            name='category',
            field=models.CharField(choices=[('firstcommandment', 'First Commandment'), ('secondcommandment', 'Second Commandment'), ('thirdcommandment', 'Third Commandment'), ('fourthcommandment', 'Fourth Commandment'), ('fifthcommandment', 'Fifth Commandment'), ('sixthcommandment', 'Sixth Commandment'), ('seventhcommandment', 'Seventh Commandment'), ('eighthcommandment', 'Eighth Commandment'), ('ninthcommandment', 'Ninth Commandment'), ('tenthcommandment', 'Tenth Commandment')], default=commandments_app.models.commandment_categories.CommandmentCategories('First Commandment'), max_length=64),
        ),
    ]
