# Generated by Django 2.2.3 on 2019-08-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0004_fileurl_imageurl_question_sermonurl_songurl_video_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='commandment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
