# Generated by Django 4.2.5 on 2023-12-09 18:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0004_lesson_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='activities',
            field=ckeditor.fields.RichTextField(blank=True, default=None, help_text='Beschrijf bij de les horende actititeiten, verwerkingsopdrachten of een leuke sketch. Wees creatief!', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='commandment',
            field=models.ForeignKey(blank=True, default=None, help_text='If there is a connection to a commandment/step with this lesson, connect it here', null=True, on_delete=django.db.models.deletion.CASCADE, to='commandments_app.commandment'),
        ),
    ]
