# Generated by Django 2.2.6 on 2019-12-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0005_auto_20191103_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecondaryBibleReference',
            new_name='DirectBibleReference',
        ),
        migrations.RenameModel(
            old_name='TertiaryBibleReference',
            new_name='IndirectBibleReference',
        ),
    ]
