# Generated by Django 2.2.3 on 2019-08-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0005_auto_20190807_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='files/')),
                ('title', models.TextField()),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
        ),
        migrations.RemoveField(
            model_name='fileurl',
            name='commandment',
        ),
        migrations.RemoveField(
            model_name='imageurl',
            name='commandment',
        ),
        migrations.RemoveField(
            model_name='sermonurl',
            name='commandment',
        ),
        migrations.RemoveField(
            model_name='songurl',
            name='commandment',
        ),
        migrations.RemoveField(
            model_name='videourl',
            name='commandment',
        ),
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='url',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='#'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='FileUrl',
        ),
        migrations.DeleteModel(
            name='ImageUrl',
        ),
        migrations.DeleteModel(
            name='SermonUrl',
        ),
        migrations.DeleteModel(
            name='SongUrl',
        ),
        migrations.DeleteModel(
            name='VideoUrl',
        ),
    ]
