# Generated by Django 2.2.6 on 2019-12-07 14:54

import commandments_app.models.bible_books
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0006_auto_20191207_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyBibleReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('Genesis', 'Genesis'), ('Exodus', 'Exodus'), ('Leviticus', 'Leviticus'), ('Numbers', 'Numbers'), ('Deuteronomy', 'Deuteronomy'), ('Joshua', 'Joshua'), ('Judges', 'Judges'), ('Ruth', 'Ruth'), ('SamuelFirstBook', '1 Samuel'), ('SamuelSecondBook', '2 Samuel'), ('KingsFirstBook', '1 Kings'), ('KingsSecondBook', '2 Kings'), ('ChroniclesFirstBook', '1 Chronicles'), ('ChroniclesSecondBook', '2 Chronicles'), ('Ezra', 'Ezra'), ('Nehemiah', 'Nehemiah'), ('Esther', 'Esther'), ('Job', 'Job'), ('Psalms', 'Psalms'), ('Proverbs', 'Proverbs'), ('Ecclesiastes', 'Ecclesiastes'), ('SongOfSolomon', 'Song of Solomon'), ('Isaiah', 'Isaiah'), ('Jeremiah', 'Jeremiah'), ('Lamentations', 'Lamentations'), ('Ezekiel', 'Ezekiel'), ('Daniel', 'Daniel'), ('Hosea', 'Hosea'), ('Joel', 'Joel'), ('Amos', 'Amos'), ('Obadiah', 'Obadiah'), ('Jonah', 'Jonah'), ('Micah', 'Micah'), ('Nahum', 'Nahum'), ('Habakkuk', 'Habakkuk'), ('Zephaniah', 'Zephaniah'), ('Haggai', 'Haggai'), ('Zechariah', 'Zechariah'), ('Malachi', 'Malachi'), ('Matthew', 'Matthew'), ('Mark', 'Mark'), ('Luke', 'Luke'), ('John', 'John'), ('Acts', 'Acts'), ('Romans', 'Romans'), ('CorinthiansFirstBook', '1 Corinthians'), ('CorinthiansSecondBook', '2 Corinthians'), ('Galatians', 'Galatians'), ('Ephesians', 'Ephesians'), ('Philippians', 'Philippians'), ('Colossians', 'Colossians'), ('ThessaloniansFirstBook', '1 Thessalonians'), ('ThessaloniansSecondBook', '2 Thessalonians'), ('TimothyFirstBook', '1 Timothy'), ('TimothySecondBook', '2 Timothy'), ('Titus', 'Titus'), ('Philemon', 'Philemon'), ('Hebrews', 'Hebrews'), ('James', 'James'), ('PeterFirstBook', '1 Peter'), ('PeterSecondBook', '2 Peter'), ('JohnFirstBook', '1 John'), ('JohnSecondBook', '2 John'), ('JohnThirdBook', '3 John'), ('Jude', 'Jude'), ('Revelation', 'Revelation')], default=commandments_app.models.bible_books.BibleBooks('Genesis'), max_length=32)),
                ('begin_chapter', models.IntegerField(default=1)),
                ('begin_verse', models.IntegerField(default=1)),
                ('end_chapter', models.IntegerField(default=0)),
                ('end_verse', models.IntegerField(default=0)),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
            options={
                'unique_together': {('commandment', 'book', 'begin_chapter', 'begin_verse', 'end_chapter', 'end_verse')},
            },
        ),
        migrations.CreateModel(
            name='ExampleBibleReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('Genesis', 'Genesis'), ('Exodus', 'Exodus'), ('Leviticus', 'Leviticus'), ('Numbers', 'Numbers'), ('Deuteronomy', 'Deuteronomy'), ('Joshua', 'Joshua'), ('Judges', 'Judges'), ('Ruth', 'Ruth'), ('SamuelFirstBook', '1 Samuel'), ('SamuelSecondBook', '2 Samuel'), ('KingsFirstBook', '1 Kings'), ('KingsSecondBook', '2 Kings'), ('ChroniclesFirstBook', '1 Chronicles'), ('ChroniclesSecondBook', '2 Chronicles'), ('Ezra', 'Ezra'), ('Nehemiah', 'Nehemiah'), ('Esther', 'Esther'), ('Job', 'Job'), ('Psalms', 'Psalms'), ('Proverbs', 'Proverbs'), ('Ecclesiastes', 'Ecclesiastes'), ('SongOfSolomon', 'Song of Solomon'), ('Isaiah', 'Isaiah'), ('Jeremiah', 'Jeremiah'), ('Lamentations', 'Lamentations'), ('Ezekiel', 'Ezekiel'), ('Daniel', 'Daniel'), ('Hosea', 'Hosea'), ('Joel', 'Joel'), ('Amos', 'Amos'), ('Obadiah', 'Obadiah'), ('Jonah', 'Jonah'), ('Micah', 'Micah'), ('Nahum', 'Nahum'), ('Habakkuk', 'Habakkuk'), ('Zephaniah', 'Zephaniah'), ('Haggai', 'Haggai'), ('Zechariah', 'Zechariah'), ('Malachi', 'Malachi'), ('Matthew', 'Matthew'), ('Mark', 'Mark'), ('Luke', 'Luke'), ('John', 'John'), ('Acts', 'Acts'), ('Romans', 'Romans'), ('CorinthiansFirstBook', '1 Corinthians'), ('CorinthiansSecondBook', '2 Corinthians'), ('Galatians', 'Galatians'), ('Ephesians', 'Ephesians'), ('Philippians', 'Philippians'), ('Colossians', 'Colossians'), ('ThessaloniansFirstBook', '1 Thessalonians'), ('ThessaloniansSecondBook', '2 Thessalonians'), ('TimothyFirstBook', '1 Timothy'), ('TimothySecondBook', '2 Timothy'), ('Titus', 'Titus'), ('Philemon', 'Philemon'), ('Hebrews', 'Hebrews'), ('James', 'James'), ('PeterFirstBook', '1 Peter'), ('PeterSecondBook', '2 Peter'), ('JohnFirstBook', '1 John'), ('JohnSecondBook', '2 John'), ('JohnThirdBook', '3 John'), ('Jude', 'Jude'), ('Revelation', 'Revelation')], default=commandments_app.models.bible_books.BibleBooks('Genesis'), max_length=32)),
                ('begin_chapter', models.IntegerField(default=1)),
                ('begin_verse', models.IntegerField(default=1)),
                ('end_chapter', models.IntegerField(default=0)),
                ('end_verse', models.IntegerField(default=0)),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
            options={
                'unique_together': {('commandment', 'book', 'begin_chapter', 'begin_verse', 'end_chapter', 'end_verse')},
            },
        ),
        migrations.CreateModel(
            name='DuplicateBibleReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('Genesis', 'Genesis'), ('Exodus', 'Exodus'), ('Leviticus', 'Leviticus'), ('Numbers', 'Numbers'), ('Deuteronomy', 'Deuteronomy'), ('Joshua', 'Joshua'), ('Judges', 'Judges'), ('Ruth', 'Ruth'), ('SamuelFirstBook', '1 Samuel'), ('SamuelSecondBook', '2 Samuel'), ('KingsFirstBook', '1 Kings'), ('KingsSecondBook', '2 Kings'), ('ChroniclesFirstBook', '1 Chronicles'), ('ChroniclesSecondBook', '2 Chronicles'), ('Ezra', 'Ezra'), ('Nehemiah', 'Nehemiah'), ('Esther', 'Esther'), ('Job', 'Job'), ('Psalms', 'Psalms'), ('Proverbs', 'Proverbs'), ('Ecclesiastes', 'Ecclesiastes'), ('SongOfSolomon', 'Song of Solomon'), ('Isaiah', 'Isaiah'), ('Jeremiah', 'Jeremiah'), ('Lamentations', 'Lamentations'), ('Ezekiel', 'Ezekiel'), ('Daniel', 'Daniel'), ('Hosea', 'Hosea'), ('Joel', 'Joel'), ('Amos', 'Amos'), ('Obadiah', 'Obadiah'), ('Jonah', 'Jonah'), ('Micah', 'Micah'), ('Nahum', 'Nahum'), ('Habakkuk', 'Habakkuk'), ('Zephaniah', 'Zephaniah'), ('Haggai', 'Haggai'), ('Zechariah', 'Zechariah'), ('Malachi', 'Malachi'), ('Matthew', 'Matthew'), ('Mark', 'Mark'), ('Luke', 'Luke'), ('John', 'John'), ('Acts', 'Acts'), ('Romans', 'Romans'), ('CorinthiansFirstBook', '1 Corinthians'), ('CorinthiansSecondBook', '2 Corinthians'), ('Galatians', 'Galatians'), ('Ephesians', 'Ephesians'), ('Philippians', 'Philippians'), ('Colossians', 'Colossians'), ('ThessaloniansFirstBook', '1 Thessalonians'), ('ThessaloniansSecondBook', '2 Thessalonians'), ('TimothyFirstBook', '1 Timothy'), ('TimothySecondBook', '2 Timothy'), ('Titus', 'Titus'), ('Philemon', 'Philemon'), ('Hebrews', 'Hebrews'), ('James', 'James'), ('PeterFirstBook', '1 Peter'), ('PeterSecondBook', '2 Peter'), ('JohnFirstBook', '1 John'), ('JohnSecondBook', '2 John'), ('JohnThirdBook', '3 John'), ('Jude', 'Jude'), ('Revelation', 'Revelation')], default=commandments_app.models.bible_books.BibleBooks('Genesis'), max_length=32)),
                ('begin_chapter', models.IntegerField(default=1)),
                ('begin_verse', models.IntegerField(default=1)),
                ('end_chapter', models.IntegerField(default=0)),
                ('end_verse', models.IntegerField(default=0)),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
            options={
                'unique_together': {('commandment', 'book', 'begin_chapter', 'begin_verse', 'end_chapter', 'end_verse')},
            },
        ),
    ]
