# Generated by Django 2.2.3 on 2019-08-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0006_auto_20190807_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sermon',
            name='author',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
