# Generated by Django 2.2.3 on 2019-08-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0007_auto_20190807_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('file', models.ImageField(upload_to='files/')),
            ],
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
