# Generated by Django 2.2.6 on 2019-12-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0007_duplicatebiblereference_examplebiblereference_studybiblereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='target_audience',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='target_audience',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='drawing',
            name='target_audience',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='movie',
            name='target_audience',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='picture',
            name='target_audience',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sermon',
            name='target_audience',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shortmovie',
            name='target_audience',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='song',
            name='target_audience',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='testimony',
            name='target_audience',
            field=models.CharField(default='', max_length=64),
        ),
    ]
