# Generated by Django 4.2.5 on 2023-09-30 08:15

import commandments_app.models.lesson_categories
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0009_alter_blog_language_alter_book_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('biblebooks', models.CharField(max_length=256)),
                ('category', models.CharField(choices=[('oldtestament', 'Old Testament'), ('newtestament', 'New Testament')], default=commandments_app.models.lesson_categories.LessonCategories['oldtestament'], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ChildrensQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.lesson')),
            ],
            options={
                'unique_together': {('lesson', 'text')},
            },
        ),
    ]
