# Generated by Django 2.2.4 on 2019-08-11 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0010_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Drawing',
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('author', models.CharField(default='', max_length=64)),
                ('url', models.URLField(default='#')),
                ('is_public', models.BooleanField(default=False)),
                ('commandment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandments_app.Commandment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
