# Generated by Django 2.2.4 on 2019-08-12 19:21

from django.db import migrations, models
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0012_auto_20190811_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', url_or_relative_url_field.fields.URLOrRelativeURLField()),
            ],
        ),
    ]
