# Generated by Django 4.2.5 on 2023-10-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0012_remove_blog_lesson_remove_book_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarylessonbiblereference',
            name='biblereference_ptr',
        ),
        migrations.RemoveField(
            model_name='primarylessonbiblereference',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='DirectLessonBibleReference',
        ),
        migrations.DeleteModel(
            name='PrimaryLessonBibleReference',
        ),
    ]
