# Generated by Django 2.2.4 on 2019-08-14 09:29

from django.db import migrations
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0013_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default='#'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default='#'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default='#'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default='#'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default='#'),
        ),
        migrations.AlterField(
            model_name='shortmovie',
            name='url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default='#'),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default='#'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(default='#'),
        ),
    ]
