# Generated by Django 4.2.5 on 2023-10-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0014_primarylessonbiblereference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', help_text='Is this Bible text positive (encouraging), negative (discouraging) or both?', max_length=32),
        ),
        migrations.AlterField(
            model_name='directbiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', help_text='Is this Bible text positive (encouraging), negative (discouraging) or both?', max_length=32),
        ),
        migrations.AlterField(
            model_name='directlessonbiblereference',
            name='lesson',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_lesson_bible_references', to='commandments_app.lesson'),
        ),
        migrations.AlterField(
            model_name='directlessonbiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', help_text='Is this Bible text positive (encouraging), negative (discouraging) or both?', max_length=32),
        ),
        migrations.AlterField(
            model_name='duplicatebiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', help_text='Is this Bible text positive (encouraging), negative (discouraging) or both?', max_length=32),
        ),
        migrations.AlterField(
            model_name='examplebiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', help_text='Is this Bible text positive (encouraging), negative (discouraging) or both?', max_length=32),
        ),
        migrations.AlterField(
            model_name='indirectbiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', help_text='Is this Bible text positive (encouraging), negative (discouraging) or both?', max_length=32),
        ),
        migrations.AlterField(
            model_name='otlawbiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', help_text='Is this Bible text positive (encouraging), negative (discouraging) or both?', max_length=32),
        ),
        migrations.AlterField(
            model_name='primarybiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', help_text='Is this Bible text positive (encouraging), negative (discouraging) or both?', max_length=32),
        ),
        migrations.AlterField(
            model_name='primarylessonbiblereference',
            name='lesson',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_lesson_bible_references', to='commandments_app.lesson'),
        ),
        migrations.AlterField(
            model_name='primarylessonbiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', help_text='Is this Bible text positive (encouraging), negative (discouraging) or both?', max_length=32),
        ),
        migrations.AlterField(
            model_name='studybiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', help_text='Is this Bible text positive (encouraging), negative (discouraging) or both?', max_length=32),
        ),
        migrations.AlterField(
            model_name='wisdombiblereference',
            name='positive_negative',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('both', 'both')], default='positive', help_text='Is this Bible text positive (encouraging), negative (discouraging) or both?', max_length=32),
        ),
    ]
