# Generated by Django 4.2.5 on 2023-10-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0016_alter_lessondrawing_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondrawing',
            name='lesson',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='commandments_app.lesson'),
        ),
    ]
