# Generated by Django 4.2.5 on 2023-10-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0017_alter_lessondrawing_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bible_section',
            field=models.CharField(blank=True, default='', help_text='The bible books which covers the lesson', max_length=128),
        ),
    ]
