# Generated by Django 2.2.4 on 2019-08-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0017_auto_20190824_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandment',
            old_name='description',
            new_name='devotional',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='drawing',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sermon',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shortmovie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testimony',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
