# Generated by Django 4.2.5 on 2023-10-11 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0018_lesson_bible_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='commandment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='commandments_app.commandment'),
        ),
    ]
