# Generated by Django 2.2.5 on 2019-09-07 10:13

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0020_auto_20190827_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Bible',
            },
        ),
        migrations.AlterField(
            model_name='commandment',
            name='devotional',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
