# Generated by Django 2.2.5 on 2019-09-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0022_commandment_title_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandment',
            name='quote',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='commandment',
            name='quote_source',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
