"""
Django settings for jesus_commandments_website project.
These settings are fixed settings that are not server dependent.
Please include this in a file named settings.py like this: from .base_settings import *

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from django.contrib.messages import constants as messages
from django.utils.translation import gettext_lazy

ROOT_URLCONF = 'jesus_commandments_website.urls'

# Note that for some apps order is important!
INSTALLED_APPS = [
    'vinaigrette',
    'rosetta',
    'commandments_app.apps.CommandmentsAppConfig',
    'account_app.apps.AccountAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'url_or_relative_url_field',
    'sorl.thumbnail',
    'cookielaw',
    'reversion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'commandments_app.context_processors.bible_translation',
                'commandments_app.context_processors.user_preferences',
                'commandments_app.context_processors.cache_settings',
            ],
        },
    },
]

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ('en', gettext_lazy('English')),  # First language is the default for modeltranslation
    ('nl', gettext_lazy('Dutch')),
#    ('de', gettext_lazy('German')),
#    ('fr', gettext_lazy('French')),
]

# Map django message level to Bootstrap alert, using the tag attribute
# Now message.level is the django name, message.tag is the bootstrap name.
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Rosetta settings
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_LANGUAGE_GROUPS = [
    'translators-nl',
#    'translators-de',
#    'translators-fr',
]

ROSETTA_MESSAGES_PER_PAGE = 25

# Maximum number of GET/POST parameters that will be read before a
# SuspiciousOperation (TooManyFieldsSent) is raised.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1500