from pathlib import Path

import yaml
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from walkasjesus_app.models import LawOfMessiah


DEFAULT_ACCEPTED_STATUSES = {"approved", "accept", "accepted", "yes", "y", "true", "done"}


class Command(BaseCommand):
    help = (
        "Apply reviewed step->LawOfMessiah counterparts from review YAML to related_lawofmessiah, "
        "optionally clearing related_steps afterwards."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--source",
            type=str,
            default="data/lawofmessiah/filter_output/review_related_steps_counterparts_77.yaml",
            help="Path to review YAML generated by review_related_steps_counterparts.",
        )
        parser.add_argument(
            "--section",
            choices=["one_to_one_suggestion", "step_reviews"],
            default="one_to_one_suggestion",
            help="Which section to read mappings from.",
        )
        parser.add_argument(
            "--accepted-statuses",
            type=str,
            default=",".join(sorted(DEFAULT_ACCEPTED_STATUSES)),
            help="Comma-separated statuses considered approved.",
        )
        parser.add_argument(
            "--apply-pending",
            action="store_true",
            help="Also accept rows with review_status='pending'. Useful before manual review.",
        )
        parser.add_argument(
            "--merge-existing",
            action="store_true",
            help="Merge mapped IDs with existing related_lawofmessiah instead of replacing.",
        )
        parser.add_argument(
            "--clear-related-steps",
            action="store_true",
            help="Clear related_steps M2M for laws that were updated.",
        )
        parser.add_argument(
            "--all-laws",
            action="store_true",
            help="Apply to all LawOfMessiah rows. Default behavior updates only unique positive laws.",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Preview changes without writing to database.",
        )

    def handle(self, *args, **options):
        source = Path(options["source"])
        section = options["section"]
        apply_pending = options["apply_pending"]
        merge_existing = options["merge_existing"]
        clear_related_steps = options["clear_related_steps"]
        all_laws = options["all_laws"]
        dry_run = options["dry_run"]

        accepted_statuses = {
            item.strip().lower()
            for item in (options["accepted_statuses"] or "").split(",")
            if item.strip()
        }

        if not source.exists():
            raise CommandError(f"Source file does not exist: {source}")

        with source.open("r", encoding="utf-8") as handle:
            payload = yaml.safe_load(handle) or {}

        if section not in payload:
            raise CommandError(f"Section '{section}' not found in {source}")

        step_to_law = self._build_step_mapping(
            rows=payload.get(section) or [],
            section=section,
            accepted_statuses=accepted_statuses,
            apply_pending=apply_pending,
        )

        if not step_to_law:
            self.stdout.write(self.style.WARNING("No approved mappings found. Nothing to apply."))
            return

        law_queryset = LawOfMessiah.objects.all().order_by("id")
        if not all_laws:
            law_queryset = law_queryset.filter(
                is_unique=True,
                commandment_type=LawOfMessiah.COMMANDMENT_TYPE_POSITIVE,
            )

        updated_count, cleared_steps_count, unresolved_steps = self._apply_mapping_to_laws(
            laws=list(law_queryset),
            step_to_law=step_to_law,
            merge_existing=merge_existing,
            clear_related_steps=clear_related_steps,
            dry_run=dry_run,
        )

        prefix = "DRY RUN: " if dry_run else ""
        self.stdout.write(
            self.style.SUCCESS(
                f"{prefix}Updated {updated_count} LawOfMessiah rows using {len(step_to_law)} approved step mappings."
            )
        )
        if clear_related_steps:
            self.stdout.write(self.style.SUCCESS(f"{prefix}Cleared related_steps on {cleared_steps_count} rows."))
        if unresolved_steps:
            unresolved_list = ", ".join(str(item) for item in sorted(unresolved_steps))
            self.stdout.write(self.style.WARNING(f"Unresolved related step IDs encountered in DB: {unresolved_list}"))

    def _build_step_mapping(self, rows, section, accepted_statuses, apply_pending):
        mapping = {}

        for row in rows:
            status = str((row or {}).get("review_status", "pending")).strip().lower()
            if status == "pending" and not apply_pending:
                continue
            if status != "pending" and status not in accepted_statuses:
                continue

            step_id = str((row or {}).get("step_id", "")).strip()
            proposed_law_id = str((row or {}).get("proposed_law_id", "")).strip().upper()

            if not step_id or not proposed_law_id:
                continue

            # section='step_reviews' can include duplicates by construction if edited manually;
            # latest row wins for deterministic behavior.
            mapping[step_id] = proposed_law_id

        return mapping

    def _extract_existing_related_ids(self, value):
        ids = []
        for entry in value or []:
            if isinstance(entry, dict):
                raw_id = str(entry.get("id", "")).strip().upper()
            else:
                raw_id = str(entry).strip().upper()
            if raw_id:
                ids.append(raw_id)
        return ids

    def _apply_mapping_to_laws(self, laws, step_to_law, merge_existing, clear_related_steps, dry_run):
        updated_count = 0
        cleared_steps_count = 0
        unresolved_steps = set()

        context = transaction.atomic() if not dry_run else _NoopContextManager()
        with context:
            for law in laws:
                step_ids = [str(step_id) for step_id in law.related_steps.values_list("id", flat=True)]
                if not step_ids and not clear_related_steps:
                    continue

                mapped_ids = []
                for step_id in step_ids:
                    mapped_law_id = step_to_law.get(step_id)
                    if mapped_law_id:
                        if mapped_law_id != law.id:
                            mapped_ids.append(mapped_law_id)
                    else:
                        unresolved_steps.add(step_id)

                if merge_existing:
                    mapped_ids.extend(self._extract_existing_related_ids(law.related_lawofmessiah))

                new_related = sorted(set(mapped_ids))

                changed = law.related_lawofmessiah != new_related
                if changed:
                    updated_count += 1
                    if not dry_run:
                        law.related_lawofmessiah = new_related
                        law.save(update_fields=["related_lawofmessiah"])

                if clear_related_steps and step_ids:
                    cleared_steps_count += 1
                    if not dry_run:
                        law.related_steps.clear()

        return updated_count, cleared_steps_count, unresolved_steps


class _NoopContextManager:
    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        return False
