import os
"""
Django settings for walkasjesus_website project.
These settings are fixed settings that are not server dependent.
Please include this in a file named settings.py like this: from .base_settings import *

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from django.contrib.messages import constants as messages
from django.utils.translation import gettext_lazy

ROOT_URLCONF = 'walkasjesus_website.urls'

# Note that for some apps order is important!
INSTALLED_APPS = [
    'vinaigrette',
    'rosetta',
    'walkasjesus_app.apps.CommandmentsAppConfig',
    'account_app.apps.AccountAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'url_or_relative_url_field',
    'sorl.thumbnail',
    'cookielaw',
    'reversion',
    'django_ckeditor_5',
]

customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]

CKEDITOR_5_CUSTOM_CSS = 'path_to.css' # optional
CKEDITOR_5_FILE_STORAGE = "path_to_storage.CustomStorage" # optional
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
        'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}

# Define a constant in settings.py to specify file upload permissions
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"  # Possible values: "staff", "authenticated", "any"

CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'walkasjesus_app.middleware.PermissionsPolicyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'walkasjesus_app.middleware.LocalizedUrlRedirectMiddleware',
    'walkasjesus_website.middleware.GeoLocationRedirectMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'walkasjesus_app.context_processors.bible_translation',
                'walkasjesus_app.context_processors.user_preferences',
                'walkasjesus_app.context_processors.cache_settings',
            ],
        },
    },
]

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ('en', gettext_lazy('English')),  # First language is the default for modeltranslation
    ('nl', gettext_lazy('Dutch')),
#    ('de', gettext_lazy('German')),
#    ('fr', gettext_lazy('French')),
]

# Map django message level to Bootstrap alert, using the tag attribute
# Now message.level is the django name, message.tag is the bootstrap name.
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Rosetta settings
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_LANGUAGE_GROUPS = [
    'translators-nl',
#    'translators-de',
#    'translators-fr',
]

ROSETTA_MESSAGES_PER_PAGE = 25

# Maximum number of GET/POST parameters that will be read before a
# SuspiciousOperation (TooManyFieldsSent) is raised.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1500

# Bible text retrieval settings
# 6 months default for verse text caching (seconds)
BIBLE_API_CACHE_TIMEOUT_SECONDS = 60 * 60 * 24 * 30 * 6
# 6 months default for commentary cache (translations + frontend commentary cache)
COMMENTARY_CACHE_TIMEOUT_SECONDS = 60 * 60 * 24 * 30 * 6
# Commentary endpoint defaults to BijbelAPI and supports optional x-api-key auth.
COMMENTARY_API_URL = os.getenv('COMMENTARY_API_URL', 'https://www.bijbelapi.com/api/commentary')
BIJBEL_API_KEY = os.getenv('BIJBEL_API_KEY', '')
# Optional legal/copyright footer shown under David Stern NT commentary.
DAVID_STERN_COMMENTARY_FOOTER_TEXT = ''
# Restrict David Stern commentary to authenticated users only.
DAVID_STERN_COMMENTARY_LOGGED_IN_ONLY = False
# Disable selected commentators in UI and proxy by ID (e.g. david-stern, matthew-henry, sword-lightfoot-en).
# Covers all commentary sources regardless of type (Scriptura API, SWORD, etc.).
COMMENTARY_DISABLED_SOURCES = []

# Imported CrossWire SWORD commentary support.
SWORD_COMMENTARY_ENABLED = True
# Import configuration for local SWORD commentary modules.
# Per-source fields:
#   enabled (bool, default True)      - show/hide this source globally
#   native_language (str, e.g. 'en')  - the language the commentary text is written in
#   auto_translate (bool, default False) - automatically machine-translate to the UI language
#                                          when native_language differs from the request language
SWORD_COMMENTARY_IMPORT_SOURCES = [
    {
        'id': 'sword-lightfoot-en',
        'module': 'Lightfoot',
        'import_format': 'mod2imp',
        'path': 'data/commentaries/en_lightfoot',
        'language': 'en',
        'label': 'John Lightfoot',
        'copyright_text': 'Public Domain',
        'sort_order': 30,
        'enabled': True,
        'native_language': 'en',
        'auto_translate': True,
    },
    {
        'id': 'sword-kingcomments-en',
        'module': 'KingComments',
        'path': 'data/commentaries/en_kingcomments',
        'language': 'en',
        'label': 'King',
        'copyright_text': 'Copyrighted; Free non-commercial distribution',
        'sort_order': 20,
        'enabled': True,
        'native_language': 'en',
        'auto_translate': False,
    },
    {
        'id': 'sword-kingcomments-nl',
        'module': 'DutKingComments',
        'path': 'data/commentaries/nl_kingcomments',
        'language': 'nl',
        'label': 'King',
        'copyright_text': 'Copyrighted; Free non-commercial distribution',
        'sort_order': 20,
        'enabled': True,
        'native_language': 'nl',
        'auto_translate': False,
    },
    {
        'id': 'sword-dutkant-nl',
        'module': 'DutKant',
        'import_format': 'mod2imp',
        'path': 'data/commentaries/nl_statenvertaling_kanttekeningen',
        'language': 'nl',
        'label': 'Statenvertaling Kanttekeningen',
        'copyright_text': 'Public Domain',
        'sort_order': 10,
        'enabled': True,
        'native_language': 'nl',
        'auto_translate': False,
    },
]

# Local Complete Jewish Bible (David H. Stern, NT source) selector settings.
CJB_BIBLE_ID = 'jnt-stern-en'
CJB_BIBLE_NAME = 'Complete Jewish Bible (David H. Stern, NT)'
CJB_BIBLE_ENABLED = True
CJB_BIBLE_LOGGED_IN_ONLY = False
# Verse count above which passages are manual "Click to retrieve"
BIBLE_AUTO_LOAD_VERSE_LIMIT = 5
# Maximum number of verses the user can select simultaneously on the Bible Study page.
BIBLE_STUDY_MAX_VERSES = 5
# Default Bible Study translations per language when no bible_id query params are provided.
# Example: {'EN': ['kjv'], 'NL': ['hsv']}
BIBLE_STUDY_DEFAULT_BIBLE_IDS_BY_LANGUAGE = {}
# Local on-disk chapter metadata index used by Bible Study type-ahead chapter lookups.
# The index can be generated one-time via:
#   python manage.py build_bible_study_chapter_index
BIBLE_STUDY_CHAPTER_INDEX_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data', 'bible_study_chapter_index.json')
# Use one primary bible for index generation and as fallback for all bible_id lookups.
# Verse/chapter structure is shared across translations, so this avoids per-translation API scans.
BIBLE_STUDY_CHAPTER_INDEX_PRIMARY_BIBLE_ID = 'de4e12af7f28f599-01'
# Limit one-time builds by default to selected books to keep API usage low.
BIBLE_STUDY_CHAPTER_INDEX_DEFAULT_BOOKS = ['Genesis']
# Keep False to avoid expensive full-bible scans during regular requests.
BIBLE_STUDY_CHAPTER_INDEX_AUTOBUILD = False
# Keep False in production to avoid API usage during user requests when index data is missing.
BIBLE_STUDY_CHAPTER_INDEX_ALLOW_LIVE_FETCH = False
# Retry transient network failures while running the explicit build command.
BIBLE_STUDY_CHAPTER_INDEX_RETRY_ATTEMPTS = 3
# Set to True only for debugging: disables Django cache usage (forces fresh loads)
DISABLE_CACHE_FOR_DEBUG = False
