# Generated by Django 6.0.3 on 2026-04-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0007_alter_blog_language_alter_book_language_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='primarybiblereference',
            constraint=models.UniqueConstraint(
                fields=('commandment',),
                name='unique_primary_reference_per_commandment',
            ),
        ),
    ]
