# Generated by Django 6.0.4 on 2026-04-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0008_alter_blog_language_alter_book_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawOfMessiah',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('source_dataset', models.CharField(default='ot', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('commandment', models.TextField(blank=True, default='')),
                ('commandment_type', models.CharField(blank=True, default='', max_length=64)),
                ('commandment_form', models.CharField(blank=True, default='', max_length=64)),
                ('category', models.CharField(blank=True, default='', max_length=256)),
                ('commentary_rudolph', models.TextField(blank=True, default='')),
                ('commentary_juster', models.TextField(blank=True, default='')),
                ('classical_commentators', models.TextField(blank=True, default='')),
                ('bible_references', models.JSONField(blank=True, default=dict)),
                ('commandments_related_ot', models.JSONField(blank=True, default=list)),
                ('commandments_related_nt', models.JSONField(blank=True, default=list)),
                ('maimonides', models.JSONField(blank=True, default=list)),
                ('meir', models.JSONField(blank=True, default=list)),
                ('chinuch', models.JSONField(blank=True, default=list)),
                ('ncla', models.CharField(blank=True, default='', max_length=128)),
                ('ncla_deviation', models.BooleanField(default=False)),
                ('classical_commandment', models.BooleanField(default=False)),
                ('source', models.URLField(blank=True, default='', max_length=1024)),
                ('copyright', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Law of Messiah',
                'verbose_name_plural': 'Law of Messiah',
                'ordering': ['id'],
            },
        ),
    ]
