# Generated by Django 6.0.4 on 2026-04-17

import django.db.models.deletion
import json
from django.db import migrations, models


NCLA_VALID_CODES = {
    f'{person}{application}'
    for person in ['JM', 'JF', 'KM', 'KF', 'GM', 'GF']
    for application in ['m', 'r', 'o', 'n', 'u', 'p', 'i']
}


def copy_bible_reference_dict_to_rows(apps, schema_editor):
    LawOfMessiah = apps.get_model('commandments_app', 'LawOfMessiah')
    LawOfMessiahBibleReference = apps.get_model('commandments_app', 'LawOfMessiahBibleReference')

    for item in LawOfMessiah.objects.all().iterator():
        bible_references = item.bible_references or {}
        for reference_type, references in bible_references.items():
            if not references:
                continue
            if not isinstance(references, list):
                references = [references]
            for order, reference in enumerate(references):
                ref_text = str(reference).strip()
                if not ref_text:
                    continue
                LawOfMessiahBibleReference.objects.create(
                    law_of_messiah_id=item.pk,
                    reference_type=reference_type,
                    reference=ref_text,
                    reference_order=order,
                )


def normalize_law_of_messiah_fields(apps, schema_editor):
    LawOfMessiah = apps.get_model('commandments_app', 'LawOfMessiah')

    for item in LawOfMessiah.objects.all().iterator():
        source_dataset_raw = str(item.source_dataset or '').strip().lower()
        item.source_dataset = 'nt' if source_dataset_raw == 'nt' else 'ot'

        commandment_type_raw = str(item.commandment_type or '').strip().lower().replace('&', 'and')
        if 'positive' in commandment_type_raw and 'negative' in commandment_type_raw:
            item.commandment_type = 'both'
        elif commandment_type_raw == 'negative':
            item.commandment_type = 'negative'
        else:
            item.commandment_type = 'positive'

        commandment_form_raw = str(item.commandment_form or '').strip().lower()
        item.commandment_form = 'implicit' if commandment_form_raw == 'implicit' else 'explicit'

        ncla_value = item.ncla
        if isinstance(ncla_value, list):
            ncla_candidates = ncla_value
        else:
            ncla_candidates = str(ncla_value or '').split()
        item.ncla = sorted({code for code in ncla_candidates if code in NCLA_VALID_CODES})

        item.save(update_fields=['source_dataset', 'commandment_type', 'commandment_form', 'ncla'])


def normalize_ncla_text_to_json_string(apps, schema_editor):
    LawOfMessiah = apps.get_model('commandments_app', 'LawOfMessiah')

    for item in LawOfMessiah.objects.all().iterator():
        ncla_value = item.ncla
        if isinstance(ncla_value, list):
            ncla_candidates = ncla_value
        else:
            ncla_candidates = str(ncla_value or '').split()
        normalized = sorted({code for code in ncla_candidates if code in NCLA_VALID_CODES})
        item.ncla = json.dumps(normalized)
        item.save(update_fields=['ncla'])


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0009_lawofmessiah_alter_blog_language_alter_book_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawOfMessiahBibleReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('key_nt_scriptures', 'Key NT Scriptures'), ('key_ot_scriptures', 'Key OT Scriptures'), ('supportive_nt_scriptures', 'Supportive NT Scriptures'), ('supportive_ot_scriptures', 'Supportive OT Scriptures')], max_length=32)),
                ('reference', models.CharField(max_length=256)),
                ('reference_order', models.PositiveIntegerField(default=0)),
                ('law_of_messiah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_reference_rows', to='commandments_app.lawofmessiah')),
            ],
            options={
                'ordering': ['reference_type', 'reference_order', 'id'],
            },
        ),
        migrations.RunPython(copy_bible_reference_dict_to_rows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='lawofmessiah',
            name='bible_references',
        ),
        migrations.AlterField(
            model_name='lawofmessiah',
            name='source_dataset',
            field=models.CharField(choices=[('ot', 'Old Testament'), ('nt', 'New Testament')], default='ot', max_length=16),
        ),
        migrations.AlterField(
            model_name='lawofmessiah',
            name='commandment_type',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('both', 'Positive & Negative')], default='positive', max_length=64),
        ),
        migrations.AlterField(
            model_name='lawofmessiah',
            name='commandment_form',
            field=models.CharField(choices=[('explicit', 'Explicit'), ('implicit', 'Implicit')], default='explicit', max_length=64),
        ),
        migrations.RunPython(normalize_ncla_text_to_json_string, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lawofmessiah',
            name='ncla',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(normalize_law_of_messiah_fields, migrations.RunPython.noop),
    ]
