# Generated by Django 6.0.4 on 2026-04-17

from django.db import migrations, models


def migrate_commandment_form_values(apps, schema_editor):
    LawOfMessiah = apps.get_model('commandments_app', 'LawOfMessiah')

    for item in LawOfMessiah.objects.all().iterator():
        value = str(item.commandment_form or '').strip().lower()
        if value == 'implicit':
            item.commandment_form = 'implied'
        elif value in ('', '-', 'none', 'null'):
            item.commandment_form = ''
        elif value != 'explicit' and value != 'implied':
            item.commandment_form = 'explicit'
        item.save(update_fields=['commandment_form'])


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0011_lawofmessiah_bible_reference_parsed_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_commandment_form_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lawofmessiah',
            name='commandment_form',
            field=models.CharField(blank=True, choices=[('', '-'), ('explicit', 'Explicit'), ('implied', 'Implied')], default='', max_length=64),
        ),
    ]
