# Generated by Django 6.0.4 on 2026-04-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0012_lawofmessiah_commandment_form_implied_or_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawofmessiahbiblereference',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='lawofmessiahbiblereference',
            name='reference_order',
        ),
    ]
