# Generated by Django 6.0.4 on 2026-04-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0014_alter_lawofmessiahbiblereference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawofmessiah',
            name='related_steps',
            field=models.ManyToManyField(blank=True, related_name='law_of_messiah_related_steps', to='commandments_app.commandment'),
        ),
    ]
