# Generated by Django 6.0.4 on 2026-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0019_lawofmessiah_ncla_structured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maimonides',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('commandment_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=32)),
                ('commandment', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Maimonides commandment',
                'verbose_name_plural': 'Maimonides commandments',
                'ordering': ['id'],
            },
        ),
    ]
