# Generated by Django 6.0.5 on 2026-05-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0023_alter_commandment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaResource',
            fields=[
            ],
            options={
                'verbose_name': 'Media Resource',
                'verbose_name_plural': 'Media Resources',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commandments_app.lawofmessiahdrawing',),
        ),
        migrations.AlterModelOptions(
            name='commandment',
            options={'ordering': ['id'], 'verbose_name': 'Step', 'verbose_name_plural': 'Steps'},
        ),
        migrations.AlterModelOptions(
            name='maimonides',
            options={'ordering': ['id'], 'verbose_name': 'Maimonides commandment', 'verbose_name_plural': 'Maimonides Commandments'},
        ),
    ]
