# Generated by Django 6.0.4 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0024_mediaresource_alter_commandment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maimonides',
            name='chinuch',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maimonides',
            name='chinuch_scriptures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maimonides',
            name='meir',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maimonides',
            name='meir_scriptures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maimonides',
            name='rudolph',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maimonides',
            name='scriptures',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
