# Generated by Django 6.0.4 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0025_maimonides_cross_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaimonidesBibleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('maimonides_scriptures', 'Maimonides Scriptures'), ('meir_scriptures', 'Meir Scriptures'), ('chinuch_scriptures', 'HaChinuch Scriptures')], max_length=32)),
                ('source_code', models.CharField(blank=True, default='', max_length=32)),
                ('book', models.CharField(choices=[('Genesis', 'Genesis'), ('Exodus', 'Exodus'), ('Leviticus', 'Leviticus'), ('Numbers', 'Numbers'), ('Deuteronomy', 'Deuteronomy'), ('Joshua', 'Joshua'), ('Judges', 'Judges'), ('Ruth', 'Ruth'), ('Samuel_1', '1 Samuel'), ('Samuel_2', '2 Samuel'), ('Kings_1', '1 Kings'), ('Kings_2', '2 Kings'), ('Chronicles_1', '1 Chronicles'), ('Chronicles_2', '2 Chronicles'), ('Ezra', 'Ezra'), ('Nehemiah', 'Nehemiah'), ('Esther', 'Esther'), ('Job', 'Job'), ('Psalm', 'Psalms'), ('Proverbs', 'Proverbs'), ('Ecclesiastes', 'Ecclesiastes'), ('Song_of_Songs', 'Song of Songs'), ('Isaiah', 'Isaiah'), ('Jeremiah', 'Jeremiah'), ('Lamentations', 'Lamentations'), ('Ezekiel', 'Ezekiel'), ('Daniel', 'Daniel'), ('Hosea', 'Hosea'), ('Joel', 'Joel'), ('Amos', 'Amos'), ('Obadiah', 'Obadiah'), ('Jonah', 'Jonah'), ('Micah', 'Micah'), ('Nahum', 'Nahum'), ('Habakkuk', 'Habakkuk'), ('Zephaniah', 'Zephaniah'), ('Haggai', 'Haggai'), ('Zechariah', 'Zechariah'), ('Malachi', 'Malachi'), ('Matthew', 'Matthew'), ('Mark', 'Mark'), ('Luke', 'Luke'), ('John', 'John'), ('Acts', 'Acts'), ('Romans', 'Romans'), ('Corinthians_1', '1 Corinthians'), ('Corinthians_2', '2 Corinthians'), ('Galatians', 'Galatians'), ('Ephesians', 'Ephesians'), ('Philippians', 'Philippians'), ('Colossians', 'Colossians'), ('Thessalonians_1', '1 Thessalonians'), ('Thessalonians_2', '2 Thessalonians'), ('Timothy_1', '1 Timothy'), ('Timothy_2', '2 Timothy'), ('Titus', 'Titus'), ('Philemon', 'Philemon'), ('Hebrews', 'Hebrews'), ('James', 'James'), ('Peter_1', '1 Peter'), ('Peter_2', '2 Peter'), ('John_1', '1 John'), ('John_2', '2 John'), ('John_3', '3 John'), ('Jude', 'Jude'), ('Revelation', 'Revelation')], default='Genesis', help_text='The bible book like Genesis, Exodus, etc.', max_length=32)),
                ('begin_chapter', models.IntegerField(default=0)),
                ('begin_verse', models.IntegerField(default=0)),
                ('end_chapter', models.IntegerField(default=0)),
                ('end_verse', models.IntegerField(default=0)),
                ('maimonides', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='bible_reference_rows', to='commandments_app.maimonides')),
            ],
            options={
                'ordering': ['reference_type', 'source_code', 'book', 'begin_chapter', 'begin_verse', 'end_chapter', 'end_verse', 'id'],
            },
        ),
    ]
