# Generated by Django 6.0.5 on 2026-06-05 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0028_restricted_cjb_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwordCommentarySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=64, unique=True)),
                ('module_name', models.CharField(default='', max_length=128)),
                ('display_name', models.CharField(default='', max_length=128)),
                ('language', models.CharField(default='en', max_length=8)),
                ('copyright_text', models.TextField(blank=True, default='')),
                ('source_path', models.CharField(default='', max_length=512)),
                ('sort_order', models.IntegerField(default=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', 'display_name', 'source_id'],
            },
        ),
        migrations.CreateModel(
            name='SwordCommentaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=32)),
                ('book_key', models.CharField(db_index=True, max_length=32)),
                ('chapter', models.PositiveIntegerField()),
                ('verse', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='commandments_app.swordcommentarysource')),
            ],
            options={
                'ordering': ['source_id', 'book', 'chapter', 'verse'],
                'indexes': [models.Index(fields=['source', 'book_key', 'chapter'], name='commandment_source__b671b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'book_key', 'chapter', 'verse'), name='uniq_sword_source_book_chapter_verse')],
            },
        ),
    ]
