# Generated by ChatGPT on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('commandments_app', '0029_swordcommentarysource_swordcommentaryentry'),
	]

	operations = [
		migrations.CreateModel(
			name='BibleTranslationUsageDaily',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('usage_date', models.DateField(db_index=True)),
				('bible_id', models.CharField(db_index=True, max_length=64)),
				('bible_name', models.CharField(blank=True, default='', max_length=255)),
				('bible_language', models.CharField(blank=True, default='', max_length=8)),
				('source', models.CharField(choices=[('api', 'API'), ('cache', 'Cache')], db_index=True, max_length=16)),
				('endpoint', models.CharField(choices=[('study_page', 'Bible Study page'), ('verses_api', 'Bible Study verses API')], db_index=True, max_length=32)),
				('user_kind', models.CharField(choices=[('authenticated', 'Authenticated'), ('anonymous', 'Anonymous')], db_index=True, max_length=16)),
				('user_key', models.CharField(db_index=True, max_length=64)),
				('request_count', models.PositiveIntegerField(default=0)),
				('verse_count', models.PositiveIntegerField(default=0)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
			],
			options={
				'ordering': ['-usage_date', 'bible_id', 'source', 'endpoint'],
				'verbose_name': 'Bible usage report',
				'verbose_name_plural': 'Bible Usage Report',
			},
		),
		migrations.AddConstraint(
			model_name='bibletranslationusagedaily',
			constraint=models.UniqueConstraint(fields=('usage_date', 'bible_id', 'source', 'endpoint', 'user_key'), name='uniq_bible_usage_daily_bucket'),
		),
		migrations.AddIndex(
			model_name='bibletranslationusagedaily',
			index=models.Index(fields=['usage_date', 'bible_id'], name='commandment_usage_d_59f4cd_idx'),
		),
		migrations.AddIndex(
			model_name='bibletranslationusagedaily',
			index=models.Index(fields=['usage_date', 'source'], name='commandment_usage_d_ae401a_idx'),
		),
		migrations.AddIndex(
			model_name='bibletranslationusagedaily',
			index=models.Index(fields=['bible_id', 'user_key'], name='commandment_bible_i_319378_idx'),
		),
	]
