# Generated by ChatGPT on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0030_bibletranslationusagedaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisitDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(db_index=True)),
                ('page_path', models.CharField(db_index=True, max_length=512)),
                ('page_label', models.CharField(blank=True, default='', max_length=255)),
                ('language_code', models.CharField(blank=True, default='', max_length=8)),
                ('user_kind', models.CharField(choices=[('authenticated', 'Authenticated'), ('anonymous', 'Anonymous')], db_index=True, max_length=16)),
                ('user_key', models.CharField(db_index=True, max_length=64)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-usage_date', 'page_path', 'language_code'],
                'verbose_name': 'Page usage report',
                'verbose_name_plural': 'Page Usage Report',
            },
        ),
        migrations.AddConstraint(
            model_name='pagevisitdaily',
            constraint=models.UniqueConstraint(fields=('usage_date', 'page_path', 'language_code', 'user_key'), name='uniq_page_visit_daily_bucket'),
        ),
        migrations.AddIndex(
            model_name='pagevisitdaily',
            index=models.Index(fields=['usage_date', 'page_path'], name='commandment_usage_d_66dfac_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisitdaily',
            index=models.Index(fields=['usage_date', 'language_code'], name='commandment_usage_d_645ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisitdaily',
            index=models.Index(fields=['page_path', 'user_key'], name='commandment_page_pa_2525f3_idx'),
        ),
    ]
