# Generated by Django 6.0.5 on 2026-07-30 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0031_pagevisitdaily'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaReviewRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('rejection_reason', models.CharField(blank=True, choices=[('too_many_resources', 'There are already too many other media resources for this step or law.'), ('not_in_line_with_preaching', 'The media resource is not in line with the preaching we can stand behind.'), ('not_compact_or_encouraging', 'The media resource is not compelling enough; we are looking for more compact, encouraging teaching.')], default='', max_length=64)),
                ('history', models.TextField(blank=True, default='')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_review_requests', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='commandments_app.mediaresource')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_reviews_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media review request',
                'verbose_name_plural': 'Media review requests',
                'ordering': ['-requested_at', '-pk'],
            },
        ),
    ]
