# Generated by Django 6.0.5 on 2026-07-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0032_mediareviewrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediareviewrequest',
            options={'ordering': ['-requested_at', '-pk'], 'permissions': [('can_review_media_resources', 'Can review media resources')], 'verbose_name': 'Media review request', 'verbose_name_plural': 'Media review requests'},
        ),
    ]
