# Generated by Django 6.0.5 on 2026-09-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0034_bibletranslationusagedaily_blocked_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCoverageReportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Media coverage report',
                'verbose_name_plural': 'Media coverage report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commandments_app.mediaresource',),
        ),
        migrations.CreateModel(
            name='MediaReviewDashboardProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Media review dashboard',
                'verbose_name_plural': 'Media review dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commandments_app.mediaresource',),
        ),
        migrations.CreateModel(
            name='MediaReviewReportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Media review report',
                'verbose_name_plural': 'Media review report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commandments_app.mediaresource',),
        ),
        migrations.AddField(
            model_name='bibletranslationusagedaily',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
