# Generated by Django 6.0.5 on 2026-09-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandments_app', '0035_mediacoveragereportproxy_mediareviewdashboardproxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisitdaily',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
